micronaut:
  application:
    name: demo
  metrics:
    enabled: true
    export:
      jmx:
        enabled: true
        step: PT1M
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      webjars:
        paths: classpath:META-INF/resources/webjars
        mapping: /webjars/**
      aux:
        paths: classpath:views
        mapping: /views/**
---
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
